name: travel_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/img/porfile1.jpg
     - assets/img/profile2.jpg
     - assets/img/porfile3.jpg
     - assets/img/lago1.jpg
     - assets/img/lago2.jpg
     - assets/img/lago3.jpg